import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page,manager=true){
 const context:any={can_manage:manager,config:{event_id:'event',team_number:4418,tba_event_key:'2026test',nexus_event_key:'demo1234',version:1},matches:[],templates:[{id:'template',name:'Student-built preflight',description:'',kind:'pre',active:true,version:1,items:[{text:'Latch check',required:true,blocking:true,area_id:null}]}],runs:[],items:[],links:[],areas:[]};
 const match={key:'2026test_qm17',label:'Q17',level:'qm',number:17,set:1,red:['4418','1619','1339'],blue:['2996','3648','4593'],alliance:'red',scheduled:1800000000000,predicted:null,actual:null,completed:false,redScore:null,blueScore:null,winner:''};
 const feed:any={eventId:'event',configured:true,configVersion:1,eventKey:'2026test',team:4418,eventName:'KCMT test fixture',matches:[match],tbaAt:Date.now(),tbaError:null,nexus:{asOf:Date.now(),nowQueuing:'Qualification 17',announcements:[],matches:[{label:'Qualification 17',status:'Now queuing',red:match.red,blue:match.blue,queue:Date.now()+600000,estimated:Date.now()+1200000,committed:null,replayOf:null}]},nexusAt:Date.now(),nexusError:null};
 const profile={id:'person',display_name:'Test Crew',role:manager?'mentor':'student',active:true};const data:any={profiles:[profile],pit_events:[{id:'event',name:'KCMT test fixture',status:'active',start_date:'2026-10-01',end_date:'2026-10-03',location:'Test only'}],pit_issues:[],pit_batteries:[{id:'battery',battery_number:'B01',status:'READY',active:true,label:'Test',notes:''}],pit_battery_events:[],pit_issue_events:[]};const calls:any[]=[];
 await page.route('**/src/client.ts',r=>r.fulfill({contentType:'application/javascript',body:`const request=async(path,body)=>{const r=await fetch('/fixture/'+path,{method:'POST',body:JSON.stringify(body)});return {data:await r.json(),error:null}};export const configured=true,configError='';export const supabase={auth:{onAuthStateChange(cb){queueMicrotask(()=>cb('SIGNED_IN',{user:{id:'person'}}));return {data:{subscription:{unsubscribe(){}}}}},async signOut(){return {error:null}}},from(table){return {select(){return this},order(){return this},range(){return request('table/'+table,{})}}},rpc(name,args){return request('rpc/'+name,args)},functions:{invoke(name,args){return request('feed',args)}},channel(){return {on(){return this},subscribe(){return this}}},removeChannel(){}};`}));
 await page.route('**/fixture/**',async r=>{const path=new URL(r.request().url()).pathname.split('/fixture/')[1],p=r.request().postDataJSON();let result:any=null;
 if(path.startsWith('table/'))result=data[path.slice(6)]||[];
 else if(path==='feed')result=feed;
 else if(path==='rpc/pit_competition_context')result=context;
 else if(path==='rpc/pit_competition_manage'){
 calls.push(p);if(p.action==='match'){if(!p.p.match_id){context.matches.push({id:'ops',event_id:'event',match_key:match.key,battery_id:null,note:'',version:1});result='ops';}else Object.assign(context.matches[0],p.p,{version:2});}
 if(p.action==='run'){context.runs.push({id:'run',match_id:'ops',name:context.templates[0].name,kind:context.templates[0].kind,template_version:1,started_at:new Date().toISOString()});context.items.push({id:'item',run_id:'run',text:'Latch check',required:true,blocking:true,completed_at:null,completed_by:null,display_order:0,version:1});}
 if(p.action==='item')Object.assign(context.items[0],{completed_at:p.p.complete?new Date().toISOString():null,completed_by:'person',version:2});
 if(p.action==='template'){context.templates.push({...p.p,id:'new',version:1});}
 }
 await r.fulfill({json:result});});
 await page.goto('/');await expect(page.getByRole('heading',{name:'Competition dashboard'})).toBeVisible();await expect(page.getByText('Live timing unavailable — using TBA schedule',{exact:false})).toHaveCount(0);return{context,feed,data,calls};
}
const nav=(page:Page,name:string)=>page.locator('.sidebar nav').getByRole('button',{name,exact:true}).click();
test('configured dashboard, match prep, blocking checklist, battery assignment and post-match offer',async({page})=>{
 const {context,feed,data,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await expect(page.locator('.comp-next')).toContainText('Q17');await expect(page.locator('.comp-next')).toContainText('4418 · 1619 · 1339');await expect(page.locator('.comp-next')).toContainText('Now queuing');
 await page.getByRole('button',{name:'Prepare for match',exact:true}).click();await page.getByRole('button',{name:'Prepare for match',exact:true}).click();await page.getByRole('combobox',{name:'Battery',exact:true}).selectOption('battery');await page.getByRole('button',{name:'Save preparation'}).click();await expect.poll(()=>context.matches[0].battery_id).toBe('battery');expect(data.pit_batteries[0].status).toBe('READY');
 await page.getByRole('combobox',{name:'Template',exact:true}).selectOption('template');await page.getByRole('button',{name:'Start checklist',exact:true}).click();await expect(page.getByText('Complete all required-before-match checks.',{exact:true})).toBeVisible();await page.getByRole('checkbox',{name:/Latch check/}).click();await expect(page.getByRole('checkbox',{name:/Latch check/})).toBeChecked();await expect(page.getByText('Complete all required-before-match checks.',{exact:true})).toHaveCount(0);await expect.poll(()=>context.items[0].completed_by).toBe('person');
 await nav(page,'Dashboard');await expect(page.getByRole('heading',{name:'READY',exact:true})).toBeVisible();context.items[0].completed_at=null;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByRole('heading',{name:'NOT READY',exact:true})).toBeVisible();
 feed.matches[0].completed=true;feed.matches[0].redScore=50;feed.matches[0].blueScore=30;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByRole('button',{name:'Start post-match inspection',exact:true})).toBeVisible();expect(context.items[0].completed_at).toBeNull();expect(data.pit_batteries[0].status).toBe('READY');expect(calls.some(c=>c.action==='item')).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:`test-results/competition-${test.info().project.name}.png`,fullPage:true});
});
test('Nexus stale/unavailable falls back; templates are leadership only; local workspace survives outage',async({page})=>{
 const {feed}=await setup(page,false);feed.nexusError='Unavailable';await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByText('Live timing unavailable — using TBA schedule',{exact:false})).toBeVisible();await expect(page.locator('.comp-next')).toContainText('Scheduled');await expect(page.locator('.comp-next')).not.toContainText('Now queuing');
 feed.tbaError='Offline';feed.matches=[];await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.locator('.comp-next')).toContainText('Q17');
 await nav(page,'Checklists');await expect(page.getByRole('button',{name:'New template'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Student-built preflight'})).toBeVisible();await nav(page,'Batteries');await expect(page.getByText('B01',{exact:true}).first()).toBeVisible();
});
for(const kind of ['pre','post','general'])test(`checklist importance maps Required and Optional for ${kind}`,async({page})=>{
 const {calls}=await setup(page);await nav(page,'Checklists');await page.getByRole('button',{name:'New template'}).click();await page.getByLabel('Name',{exact:true}).fill('Inspection');await page.getByRole('combobox',{name:'Type',exact:true}).selectOption(kind);await page.getByLabel('Item text',{exact:true}).fill('Inspect intake');
 const importance=page.getByRole('combobox',{name:'Importance',exact:true});await expect(importance.locator('option')).toHaveText(['Required','Optional']);await expect(importance).toHaveValue('required');
 await expect(page.getByText(kind==='pre'?'Must be completed before the robot is marked ready for the match.':'Must be completed as part of the checklist.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add item',exact:true}).click();await page.getByLabel('Item text',{exact:true}).last().fill('Photo');await importance.last().selectOption('optional');await expect(page.getByText('Recommended, but not required to complete the checklist.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.at(-1)?.action).toBe('template');expect(calls.at(-1).p.items.map((i:any)=>[i.required,i.blocking])).toEqual([[true,kind==='pre'],[false,false]]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('checklist legacy required item stays non-blocking until explicitly changed',async({page})=>{
 const {context,calls}=await setup(page);context.templates[0].items[0].blocking=false;await page.getByRole('button',{name:'Refresh schedule'}).click();await nav(page,'Checklists');await page.getByRole('button',{name:'Edit / reorder'}).click();await expect(page.getByRole('combobox',{name:'Importance',exact:true})).toHaveValue('required');await expect(page.getByText('Existing required check; its non-blocking readiness behavior is preserved.',{exact:true})).toBeVisible();await page.getByLabel('Item text',{exact:true}).fill('Renamed check');await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.at(-1)?.action).toBe('template');expect(calls.at(-1).p.items[0]).toMatchObject({required:true,blocking:false});
 await page.getByRole('button',{name:'Edit / reorder'}).first().click();await page.getByRole('combobox',{name:'Importance',exact:true}).selectOption('optional');await page.getByRole('combobox',{name:'Importance',exact:true}).selectOption('required');await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.length).toBe(2);expect(calls.at(-1).p.items[0]).toMatchObject({required:true,blocking:true});expect(context.templates[0].items[0].blocking).toBe(false);
});
test('responsive at tablet for competition dashboard',async({page})=>{await page.setViewportSize({width:768,height:1024});await setup(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/competition-tablet.png',fullPage:true});});
