import {test,expect} from '@playwright/test';
import {setup,nav} from './competition-fixture';
test('configured dashboard, match prep, blocking checklist, battery assignment and post-match offer',async({page})=>{
 const {context,feed,data,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await expect(page.locator('.comp-next')).toContainText('Q17');await expect(page.locator('.comp-next')).toContainText('4418 · 1619 · 1339');await expect(page.locator('.comp-next')).toContainText('Now queuing');
 await page.getByRole('button',{name:'Open Q17',exact:true}).click();await page.getByRole('button',{name:'Prepare for match',exact:true}).click();await page.getByRole('combobox',{name:'Battery',exact:true}).selectOption('battery');await page.getByRole('button',{name:'Save preparation'}).click();await expect.poll(()=>context.matches[0].battery_id).toBe('battery');expect(data.pit_batteries[0].status).toBe('READY');
 await page.getByRole('combobox',{name:'Template',exact:true}).selectOption('template');await page.getByRole('button',{name:'Start checklist',exact:true}).click();await expect(page.getByText('Complete all required-before-match checks.',{exact:true})).toBeVisible();await page.getByRole('checkbox',{name:/Latch check/}).click();await expect(page.getByRole('checkbox',{name:/Latch check/})).toBeChecked();await expect(page.getByText('Complete all required-before-match checks.',{exact:true})).toHaveCount(0);await expect.poll(()=>context.items[0].completed_by).toBe('person');
 await nav(page,'Dashboard');await expect(page.getByRole('heading',{name:'NEEDS ATTENTION',exact:true})).toBeVisible();data.pit_batteries[0].status='ON ROBOT';await page.getByRole('button',{name:'Refresh schedule'}).click();await page.reload();await expect(page.getByRole('heading',{name:'ROBOT READY',exact:true})).toBeVisible();context.items[0].completed_at=null;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByRole('heading',{name:'ROBOT NOT READY',exact:true})).toBeVisible();
 feed.matches[0].completed=true;feed.matches[0].redScore=50;feed.matches[0].blueScore=30;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByRole('button',{name:'Start post-match inspection',exact:true})).toBeVisible();expect(context.items[0].completed_at).toBeNull();expect(data.pit_batteries[0].status).toBe('ON ROBOT');expect(calls.some(c=>c.action==='item')).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:`test-results/competition-${test.info().project.name}.png`,fullPage:true});
});
test('Nexus stale/unavailable falls back; templates are leadership only; local workspace survives outage',async({page})=>{
 const {feed}=await setup(page,false);feed.nexusError='Unavailable';await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByText('Live timing unavailable — using TBA schedule',{exact:false})).toBeVisible();await expect(page.locator('.comp-next')).toContainText('Scheduled');await expect(page.locator('.comp-next')).not.toContainText('Now queuing');
 feed.tbaError='Offline';feed.matches=[];await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.locator('.comp-next')).toContainText('Q17');
 await nav(page,'Checklists');await expect(page.getByRole('button',{name:'New template'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Student-built preflight'})).toBeVisible();await nav(page,'Batteries');await expect(page.getByRole('heading',{name:'Test',exact:true})).toBeVisible();
});
for(const kind of ['pre','post','general'])test(`checklist importance maps Required and Optional for ${kind}`,async({page})=>{
 const {calls}=await setup(page);await nav(page,'Checklists');await page.getByRole('button',{name:'New template'}).click();await page.getByLabel('Name',{exact:true}).fill('Inspection');await page.getByRole('combobox',{name:'Type',exact:true}).selectOption(kind);await page.getByLabel('Item text',{exact:true}).fill('Inspect intake');
 const importance=page.getByRole('combobox',{name:'Importance',exact:true});await expect(importance.locator('option')).toHaveText(['Required','Optional']);await expect(importance).toHaveValue('required');
 await expect(page.getByText(kind==='pre'?'Must be completed before the robot is marked ready for the match.':'Must be completed as part of the checklist.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add item',exact:true}).click();await page.getByLabel('Item text',{exact:true}).last().fill('Photo');await importance.last().selectOption('optional');await expect(page.getByText('Recommended, but not required to complete the checklist.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.at(-1)?.action).toBe('template');expect(calls.at(-1).p.items.map((i:any)=>[i.required,i.blocking])).toEqual([[true,kind==='pre'],[false,false]]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('checklist legacy required item stays non-blocking until explicitly changed',async({page})=>{
 const {context,calls}=await setup(page);context.templates[0].items[0].blocking=false;await page.getByRole('button',{name:'Refresh schedule'}).click();await nav(page,'Checklists');await page.getByRole('button',{name:'Edit / reorder'}).click();await expect(page.getByRole('combobox',{name:'Importance',exact:true})).toHaveValue('required');await expect(page.getByText('Existing required check; its non-blocking readiness behavior is preserved.',{exact:true})).toBeVisible();await page.getByLabel('Item text',{exact:true}).fill('Renamed check');await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.at(-1)?.action).toBe('template');expect(calls.at(-1).p.items[0]).toMatchObject({required:true,blocking:false});
 await page.getByRole('button',{name:'Edit / reorder'}).first().click();await page.getByRole('combobox',{name:'Importance',exact:true}).selectOption('optional');await page.getByRole('combobox',{name:'Importance',exact:true}).selectOption('required');await page.getByRole('button',{name:'Save template'}).click();await expect.poll(()=>calls.length).toBe(2);expect(calls.at(-1).p.items[0]).toMatchObject({required:true,blocking:true});expect(context.templates[0].items[0].blocking).toBe(false);
});
test('responsive at tablet for competition dashboard',async({page})=>{await page.setViewportSize({width:768,height:1024});await setup(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/competition-tablet.png',fullPage:true});});

test('dashboard progress, live turnaround, attention, announcements and stale fallback',async({page})=>{
 const {context,feed}=await setup(page);const next=feed.matches[0];next.scheduled=Date.now()+1920000;feed.nexus.matches[0].status='Queuing soon';feed.nexus.matches[0].queue=Date.now()+1080000;
 feed.matches.unshift({...next,key:'2026test_qm4',label:'Q4',number:4,completed:true,redScore:50,blueScore:30,winner:'red'});feed.matches.push({...next,key:'2026test_qm24',label:'Q24',number:24});feed.nexus.announcements=[{id:'a',text:'Field running ten minutes behind.',at:Date.now()}];
 await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.locator('.comp-next')).toContainText('Q17');await expect(page.locator('.comp-next')).toContainText('Queue in ~18 min');await expect(page.locator('.comp-timing')).toHaveClass(/warning/);await expect(page.getByRole('button',{name:'Prepare for Q17',exact:true})).toBeVisible();
 await expect(page.locator('.comp-attention')).toContainText('Battery not assigned for Q17');await expect(page.locator('.comp-progress')).toContainText('Won');await expect(page.locator('.comp-progress [aria-current]')).toContainText('Q17');await expect(page.getByText('4418: 1 of 3 published qualification matches complete')).toBeVisible();await expect(page.getByRole('heading',{name:'Event update'})).toBeVisible();await expect(page.getByText('Field running ten minutes behind.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Start post-match inspection',exact:true})).toBeVisible();
 await page.locator('.comp-progress').getByRole('button',{name:/Q4/}).click();await expect(page.getByRole('heading',{name:'Q4',exact:true})).toBeVisible();await nav(page,'Dashboard');
 feed.nexus.asOf=Date.now()-180000;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.locator('.comp-next')).toContainText('Scheduled in 32 min');await expect(page.locator('.comp-next')).not.toContainText('Queue in');await expect(page.getByRole('heading',{name:'Event update'})).toHaveCount(0);
 feed.tbaError='Offline';feed.matches=[];await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByText('Last loaded schedule may be stale',{exact:false})).toBeVisible();await expect(page.locator('.comp-next')).toContainText('Q17');expect(context.matches).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`test-results/dashboard-${test.info().project.name}.png`,fullPage:true});
});
test('dashboard hides empty attention and explains existing readiness blockers',async({page})=>{
 const {context,data}=await setup(page);data.pit_batteries[0].status='ON ROBOT';context.matches=[{id:'ops',match_key:'2026test_qm17',battery_id:'battery'}];context.runs=[{id:'run',match_id:'ops',kind:'pre'}];context.items=[{id:'item',run_id:'run',required:true,blocking:true,completed_at:new Date().toISOString()}];
 await page.reload();await expect(page.getByRole('heading',{name:'ROBOT READY',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Needs attention',exact:true})).toHaveCount(0);await expect(page.locator('.comp-readiness')).toContainText('Battery Test (B01) · ON ROBOT');
 context.items[0].completed_at=null;await page.getByRole('button',{name:'Refresh schedule'}).click();await expect(page.getByRole('heading',{name:'ROBOT NOT READY',exact:true})).toBeVisible();await expect(page.locator('.comp-readiness')).toContainText('1 required checks remaining · 1 blocking');await page.getByRole('button',{name:'View blockers',exact:true}).click();await expect(page.locator('.comp-attention')).toBeInViewport();
});
