import {test,expect,type Page} from '@playwright/test';
const issue='11111111-1111-4111-8111-111111111111',po='22222222-2222-4222-8222-222222222222',time='2026-10-05T10:00:00Z';
async function fixture(page:Page,canAttach=true){
 const profile={id:'person',display_name:'Test operator',active:true,role:canAttach?'mentor':'student'};
 const repair={id:issue,issue_number:1,title:'Replace fixture bracket',description:'Synthetic repair only',subsystem:'Intake',severity:'HIGH',status:'OPEN',event_id:'event',assigned_to:'person',reported_by:'person',created_at:time,updated_at:time,battery_id:null,discovered_match:'',root_cause:'',repair_notes:'',resolution_notes:'',resolved_at:null,resolved_by:null};
 const tables:any={profiles:[profile],pit_events:[{id:'event',name:'Fixture event',status:'active',start_date:'2026-10-05',end_date:'2026-10-07'}],pit_issues:[repair],pit_batteries:[],pit_battery_events:[],pit_issue_events:[]};
 const context:any={issue_id:issue,issue_updated_at:time,can_attach:canAttach,links:[]};const candidate:any={issue_id:issue,issue_updated_at:time,po_id:po,po_number:17,status:'submitted_to_school',requester_name:'Test requester',can_attach:canAttach};
 const calls:any[]=[];const control:{missing?:boolean;fail?:boolean;gate?:()=>Promise<void>;saveGate?:()=>Promise<void>}={};
 await page.route('https://*.supabase.co/**',route=>route.abort());
 await page.route('**/src/client.ts',route=>route.fulfill({contentType:'application/javascript',body:`const req=async(path,args)=>{const r=await fetch('/purchase-fixture/'+path,{method:'POST',body:JSON.stringify(args)});return r.json()};export const configured=true,configError='';export const supabase={auth:{onAuthStateChange(cb){window.__fixtureAuth=cb;queueMicrotask(()=>cb('SIGNED_IN',{user:{id:'person'}}));return {data:{subscription:{unsubscribe(){}}}}},async getSession(){return {data:{session:{user:{id:'person'},access_token:'synthetic-token'}},error:null}},async signOut(){return {error:null}}},from(table){return {select(){return this},order(){return this},range(){return req('table/'+table,{})}}},rpc(name,args){const query={setHeader(){return query},abortSignal(signal){query.signal=signal;return query},then(resolve,reject){if(query.signal?.aborted)return Promise.reject(new Error('aborted')).then(resolve,reject);return req('rpc/'+name,args).then(resolve,reject)}};return query},functions:{invoke(){return Promise.resolve({data:null,error:null})}},channel(){return {on(){return this},subscribe(){return this}}},removeChannel(){}};`}));
 await page.route('**/purchase-fixture/**',async route=>{
  const path=new URL(route.request().url()).pathname.split('/purchase-fixture/')[1],args=route.request().postDataJSON();let data:any=null,error:any=null;
  if(path.startsWith('table/'))data=tables[path.slice(6)]||[];
  if(path==='rpc/pit_competition_context')data={can_manage:false,config:null,matches:[],templates:[],runs:[],items:[],links:[],areas:[]};
  if(path==='rpc/pit_update_issue'){calls.push({kind:'save',args});await control.saveGate?.();}
  if(path==='rpc/finance_repair_context'){if(control.missing)error={code:'PGRST202',message:'Unavailable'};else data=context;}
  if(path==='rpc/finance_repair_po_candidate'){calls.push({kind:'preview',args});data=candidate;}
  if(path==='rpc/finance_attach_repair_po'){calls.push({kind:'attach',args});if(control.gate)await control.gate();if(control.fail)error={code:'network',message:'Uncertain'};else{context.links=[{po_id:po,po_number:17,status:candidate.status,requester_name:candidate.requester_name,linked_at:time}];data=context;}}
  await route.fulfill({json:{data,error}});
 });
 await page.goto(`/#issue/${issue}`);await expect(page.getByRole('dialog',{name:'Issue #1',exact:true})).toBeVisible();
 return {calls,control,context,candidate,repair,tables,section:page.getByRole('region',{name:'Repair purchasing'})};
}
test('PO is previewed before explicit linking, with correct workflow labels',async({page})=>{
 const {calls,repair,section}=await fixture(page);await expect(section).toContainText('No purchase orders visible here');await section.getByLabel('Existing Finance PO link or ID').fill(`https://finance.frc4418.org/#po/${po}`);await section.getByRole('button',{name:'Review purchase order'}).click();await expect(section).toContainText('PO requester: Test requester');await expect(section).toContainText('Submitted to school');expect(calls.filter(c=>c.kind==='attach')).toHaveLength(0);await expect(section.getByRole('button',{name:'Link this purchase order'})).toBeDisabled();await section.getByLabel('Why is this PO related to the repair?').fill('Replacement bracket');await section.getByRole('button',{name:'Link this purchase order'}).click();await expect(section).toContainText('Purchase order linked');expect(calls.filter(c=>c.kind==='attach')).toHaveLength(1);expect(repair.status).toBe('OPEN');await expect(section.getByRole('link',{name:'Open in Finance',exact:true})).toHaveAttribute('href',`https://finance.frc4418.org/#po/${po}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('changing reviewed PO clears preview, invalid domains never become reviewable',async({page})=>{const {section,calls}=await fixture(page);const input=section.getByLabel('Existing Finance PO link or ID');await input.fill(po);await section.getByRole('button',{name:'Review purchase order'}).click();await expect(section.getByRole('button',{name:'Link this purchase order'})).toBeVisible();await input.fill(`https://evil.test/#po/${po}`);await expect(section.getByRole('button',{name:'Link this purchase order'})).toHaveCount(0);await expect(section.getByRole('button',{name:'Review purchase order'})).toBeDisabled();expect(calls.filter(c=>c.kind==='attach')).toHaveLength(0);});
test('missing bridge is isolated from existing repair workflow',async({page})=>{const {section,control}=await fixture(page);control.missing=true;await section.getByRole('button',{name:'Refresh links'}).click();await expect(section).toContainText('not available in this workspace yet');await expect(page.getByRole('button',{name:'Save issue',exact:true})).toBeEnabled();await expect(section.getByRole('button',{name:'Review purchase order'})).toHaveCount(0);});
test('non-manager sees only permitted links without attachment controls',async({page})=>{const {section,context}=await fixture(page,false);context.links=[{po_id:po,po_number:17,status:'draft',requester_name:'Test requester',linked_at:time}];await section.getByRole('button',{name:'Refresh links'}).click();await expect(section).toContainText('PO #17');await expect(section.getByLabel('Existing Finance PO link or ID')).toHaveCount(0);});
test('uncertain attachment stops and requires an explicit status refresh',async({page})=>{const {section,control,calls}=await fixture(page);control.fail=true;await section.getByLabel('Existing Finance PO link or ID').fill(po);await section.getByRole('button',{name:'Review purchase order'}).click();await section.getByLabel('Why is this PO related to the repair?').fill('Replacement bracket');await section.getByRole('button',{name:'Link this purchase order'}).click();await expect(section).toContainText('request may already have completed');await expect(section.getByRole('button',{name:'Review purchase order'})).toBeDisabled();expect(calls.filter(c=>c.kind==='attach')).toHaveLength(1);await section.getByRole('button',{name:'Refresh links'}).click();await expect(section.getByRole('button',{name:'Review purchase order'})).toBeEnabled();expect(calls.filter(c=>c.kind==='attach')).toHaveLength(1);});
test('closing a deep-linked repair clears route and refresh does not reopen it',async({page})=>{await fixture(page);await page.getByRole('button',{name:'Close dialog'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(new URL(page.url()).hash).toBe('');await page.reload();await expect(page.getByRole('heading',{name:'Competition dashboard'})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);});
test('unavailable repair route never opens a blank detail',async({page})=>{await fixture(page);await page.goto(`/#issue/${po}`);await expect(page.getByText('This repair link is unavailable.',{exact:false})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);});
test('candidate cannot silently advance the reviewed repair version',async({page})=>{const {section,candidate,calls}=await fixture(page);candidate.issue_updated_at='2026-10-05T11:00:00Z';await section.getByLabel('Existing Finance PO link or ID').fill(po);await section.getByRole('button',{name:'Review purchase order'}).click();await expect(section).toContainText('This repair changed');await expect(section.getByRole('button',{name:'Link this purchase order'})).toHaveCount(0);expect(calls.filter(c=>c.kind==='attach')).toHaveLength(0);});

test('same-user sign-in after an identity reset can reopen the original repair route',async({page})=>{await fixture(page);await page.evaluate(()=>{(window as unknown as {__fixtureAuth:(event:string,session:unknown)=>void}).__fixtureAuth('SIGNED_IN',{user:{id:'other-fixture-user'}});});await expect(page.getByText('Your account needs an active Team 4418 profile.',{exact:false})).toBeVisible();await page.evaluate(()=>{(window as unknown as {__fixtureAuth:(event:string,session:unknown)=>void}).__fixtureAuth('SIGNED_IN',{user:{id:'person'}});});await expect(page.getByRole('dialog',{name:'Issue #1',exact:true})).toBeVisible();});

test('delayed repair save cannot close a newer deep-linked repair',async({page})=>{const {tables,repair,control,calls}=await fixture(page);tables.pit_issues.push({...repair,id:po,issue_number:2,title:'Second fixture repair'});let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);control.saveGate=()=>gate;await page.getByRole('button',{name:'Save issue',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.kind==='save').length).toBe(1);await page.evaluate(id=>{location.hash='#issue/'+id;},po);await expect(page.getByText('This repair link is unavailable.',{exact:false})).toBeVisible();release();await expect(page.getByText('Saved successfully',{exact:true})).toBeVisible();expect(new URL(page.url()).hash).toBe('#issue/'+po);});
