import {useState} from 'react';
import {canManage,canWork,type Data,type Profile} from '../model';
import {liveFor,nextMatch,operationalReadiness,type Competition,type Context,type Match,type Ops,type Template,type TemplateItem} from './service';
import './competition.css';
const when=(n:number|string|null|undefined)=>n?new Date(n).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Not published';
const blank:TemplateItem={text:'',required:true,blocking:false,area_id:null};
type Props={page:string;competition:Competition;data:Data;profile:Profile;report:(id:string)=>void;openIssue:(id:string)=>void;batteryAction:(id:string)=>void;go:(page:any)=>void};
export function CompetitionWorkspace({page,competition:c,data,profile,report,openIssue,batteryAction,go}:Props){
 const [selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<Partial<Template>|null>(null),[filter,setFilter]=useState('all');
 const d=c.context,event=data.events.find(e=>e.status==='active'),feed=c.feed;
 if(!d)return <section className="card competition"><p role={c.error?'alert':'status'}>{c.error||'Loading competition operations…'}</p><button onClick={()=>void c.refresh(true)}>Refresh</button></section>;
 const external=feed?.configured?feed.matches:[],next=nextMatch(external),ops=selected?d.matches.find(m=>m.match_key===selected):undefined,match=external.find(m=>m.key===selected);
 const act=(action:string,p:Record<string,unknown>,done?:(id:string)=>void)=>void c.run(action,p).then(id=>done?.(id)).catch(()=>{});
 const open=(key:string)=>{setSelected(key);go('matches');};
 const preItems=d.items.filter(i=>d.runs.some(r=>r.id===i.run_id&&r.kind==='pre'&&r.match_id===d.matches.find(o=>o.match_key===next?.key)?.id));
 const preStarted=d.runs.some(r=>r.kind==='pre'&&r.match_id===d.matches.find(o=>o.match_key===next?.key)?.id);
 const readiness=operationalReadiness(data.issues.filter(i=>i.event_id===event?.id),d.items,preStarted);
 const announcements=c.liveAvailable?feed?.nexus?.announcements:[];
 const live=(m:Match)=>c.liveAvailable?liveFor(m,feed?.nexus?.matches||[]):null;
 const matchCard=(m:Match)=>{const n=live(m);return <><div className="comp-match-title"><strong>{m.label}</strong><span className={'badge '+(m.alliance==='red'?'danger':'info')}>{m.alliance.toUpperCase()}</span><span>{m.completed?'Completed':m.actual?'In progress / awaiting score':m.key===next?.key?'Next':'Upcoming'}</span></div><p><strong>{m[m.alliance].join(' · ')}</strong> vs {m[m.alliance==='red'?'blue':'red'].join(' · ')}</p><p>Scheduled {when(m.scheduled)}{n?.estimated?` · Nexus estimate ${when(n.estimated)}`:m.predicted?` · TBA estimate ${when(m.predicted)}`:''}</p>{n&&<p><strong>{n.status}</strong>{n.queue?` · Queue ${when(n.queue)}`:''}</p>}{m.completed&&<p>Red {m.redScore} — Blue {m.blueScore} · {m.winner?m.winner.toUpperCase()+' wins':'Tie'}</p>}</>;};
 return <div className="competition">
 {c.error&&<p role="alert" className="error">{c.error}</p>}
 {['dashboard','matches','admin'].includes(page)&&<div className="comp-feed"><span>{feed?.eventName||event?.name||'No active event'}{d.config&&` · Team ${d.config.team_number}`}</span><button disabled={c.busy} onClick={()=>void c.refresh(true)}>Refresh schedule</button>{d.config&&<small>{c.feedError||feed?.tbaError||(!feed?'Loading external schedule…':`TBA checked ${when(feed.tbaAt)}`)} · {c.liveAvailable?'Nexus live':'Live timing unavailable — using TBA schedule'}{!c.liveAvailable&&feed?.nexus?.asOf?` (last Nexus snapshot ${when(feed.nexus.asOf)})`:''}</small>}</div>}
 {!d.config&&['dashboard','matches'].includes(page)&&<section className="card"><h2>Connect your event</h2><p>Activate a Pit event, then enter its TBA and Nexus identifiers in Event. Issues and batteries remain available.</p><button onClick={()=>go('admin')}>Event settings</button></section>}
 {page==='dashboard'&&d.config&&<>
 <div className="comp-grid"><section className="card comp-next"><small>NEXT MATCH</small>{next?<>{matchCard(next)}<button className="primary" onClick={()=>open(next.key)}>Prepare for match</button></>:<><h2>No upcoming match published</h2><p>Check the schedule and event announcements.</p></>}</section><section className="card"><small>ROBOT READINESS</small><h2 className={readiness==='NOT READY'?'comp-danger':''}>{readiness}</h2><p>{preStarted?`${preItems.filter(i=>i.completed_at).length}/${preItems.length} pre-match items complete`:'Pre-match checklist not started'}</p><p>Assigned battery: {data.batteries.find(b=>b.id===d.matches.find(o=>o.match_key===next?.key)?.battery_id)?.battery_number||'Not assigned'}</p><p>{data.issues.filter(i=>i.event_id===event?.id&&i.status!=='RESOLVED').length} open issues · {data.issues.filter(i=>i.event_id===event?.id&&i.status!=='RESOLVED'&&['HIGH','ROBOT DOWN'].includes(i.severity)).length} high/blocking</p><button onClick={()=>go('issues')}>Robot / issues</button><small>Readiness reflects recorded issues and checklist work, not an automatic inspection.</small></section></div>
 <section className="card"><h2>Upcoming matches</h2>{external.filter(m=>!m.completed&&!m.actual).slice(0,4).map(m=><button className="comp-row" key={m.key} onClick={()=>open(m.key)}>{matchCard(m)}</button>)}</section>
 {external.filter(m=>m.completed).slice(-1).map(m=><section className="card" key={m.key}><h2>After {m.label}</h2><button onClick={()=>open(m.key)}>Start post-match inspection</button><p>Battery handling and inspection require your confirmation.</p></section>)}
 </>}
 {['dashboard','admin'].includes(page)&&c.liveAvailable&&<section className="card"><h2>Live event</h2><p>Now queuing: {feed?.nexus?.nowQueuing||'Not published'}</p>{feed?.nexus?.matches.filter(m=>!m.committed&&m.status!=='Queuing soon').map(m=><p key={m.label}>{m.label} · {m.status} · estimate {when(m.estimated)}</p>)}{announcements?.map((a:{id:string;text:string;at:number|null})=><p key={a.id}><strong>{when(a.at)}</strong> {a.text}</p>)}<small>Nexus labels are shown as supplied; ambiguous playoff/replay matches are not merged into a TBA match.</small></section>}
 {page==='matches'&&!selected&&<><label>Show matches<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="upcoming">Upcoming</option><option value="completed">Completed</option></select></label>{external.filter(m=>filter==='all'||(filter==='completed'?m.completed:!m.completed)).map(m=><button className="card comp-row" key={m.key} onClick={()=>setSelected(m.key)}>{matchCard(m)}</button>)}{!external.length&&<p>No TBA schedule loaded. Existing operations remain below.</p>}{d.matches.filter(o=>!external.some(m=>m.key===o.match_key)).map(o=><button key={o.id} onClick={()=>setSelected(o.match_key)}>{o.match_key} · saved operations</button>)}</>}
 {page==='matches'&&selected&&<><button onClick={()=>setSelected(null)}>← All matches</button><section className="card"><h2>{match?.label||selected}</h2>{match&&matchCard(match)}{!ops&&<><p>Start a local operations record for this match.</p>{d.can_manage?<button className="primary" disabled={c.busy} onClick={()=>act('match',{event_id:event?.id,match_key:selected})}>Prepare for match</button>:<p>Competition leadership starts match preparation.</p>}</>}</section>{ops&&<>
 <section className="card"><h2>Match preparation</h2><p>Assigned battery: <strong>{data.batteries.find(b=>b.id===ops.battery_id)?.battery_number||'None'}</strong></p>{d.can_manage?<form key={ops.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act('match',{match_id:ops.id,version:ops.version,battery_id:f.get('battery'),note:f.get('note')});}}><label>Battery<select name="battery" defaultValue={ops.battery_id||''}><option value="">Not assigned</option>{data.batteries.filter(b=>b.active&&b.status!=='RETIRED').map(b=><option key={b.id} value={b.id}>{b.battery_number} · {b.status}</option>)}</select></label><label>Operational note<textarea name="note" maxLength={2000} defaultValue={ops.note}/></label><button disabled={c.busy}>Save preparation</button><small>Assignment does not install or change battery status.</small></form>:<p>{ops.note}</p>}{ops.battery_id&&canWork(profile)&&<button onClick={()=>batteryAction(ops.battery_id!)}>Open battery actions</button>}</section>
 {match?.completed&&<section className="card"><h2>Start post-match inspection</h2><p>Record inspection and battery removal yourself. A published score completes no physical action.</p></section>}
 <RunStarter d={d} busy={c.busy} enabled={canWork(profile)} kind={match?.completed?'post':'pre'} start={t=>act('run',{id:crypto.randomUUID(),event_id:event?.id,match_id:ops.id,template_id:t.id,template_version:t.version})}/>
 <RunList d={d} matchId={ops.id} data={data} enabled={canWork(profile)} busy={c.busy} act={act}/>
 <section className="card"><h2>Robot issues</h2>{data.issues.filter(i=>i.event_id===event?.id&&i.status!=='RESOLVED').map(i=><button className="comp-row" key={i.id} onClick={()=>openIssue(i.id)}>{i.title} · {i.severity} · {i.status}</button>)}<h3>Discovered at this match</h3>{d.links.filter(l=>l.match_id===ops.id).map(l=><button key={l.issue_id} onClick={()=>openIssue(l.issue_id)}>{data.issues.find(i=>i.id===l.issue_id)?.title||'Issue'}</button>)}{canWork(profile)&&<button onClick={()=>report(ops.id)}>Report match issue</button>}{canManage(profile)&&<form onSubmit={e=>{e.preventDefault();act('link_issue',{match_id:ops.id,issue_id:new FormData(e.currentTarget).get('issue')});}}><label>Associate existing issue<select name="issue" required><option value="">Choose issue</option>{data.issues.filter(i=>i.event_id===event?.id&&!d.links.some(l=>l.issue_id===i.id)).map(i=><option value={i.id} key={i.id}>#{i.issue_number} {i.title}</option>)}</select></label><button disabled={c.busy}>Associate issue</button></form>}</section>
 </>}</>}
 {page==='checklists'&&<><div className="comp-feed"><h2>Checklist templates</h2>{d.can_manage&&<button onClick={()=>setEditing({name:'',description:'',kind:'pre',active:true,items:[{...blank}]})}>New template</button>}</div>{editing&&<TemplateEditor key={editing.id||'new'} template={editing} d={d} busy={c.busy} cancel={()=>setEditing(null)} save={p=>act('template',p,()=>setEditing(null))}/>}<div className="comp-grid">{d.templates.map(t=><section className="card" key={t.id}><h3>{t.name}</h3><p>{t.kind==='pre'?'Pre-match':t.kind==='post'?'Post-match':'General'} · v{t.version} · {t.active?'Active':'Archived'} · {t.items.length} items</p><p>{t.description}</p>{d.can_manage&&<><button onClick={()=>setEditing(t)}>Edit / reorder</button><button onClick={()=>setEditing({...t,id:undefined,name:t.name+' copy',version:undefined,active:true})}>Duplicate</button><button disabled={c.busy} onClick={()=>act('template',{...t,active:!t.active})}>{t.active?'Archive':'Reactivate'}</button></>}</section>)}</div>{!d.templates.length&&<p>No templates yet. Leadership can add your team’s procedure.</p>}{event&&<RunStarter d={d} busy={c.busy} enabled={canWork(profile)} kind="general" start={t=>act('run',{id:crypto.randomUUID(),event_id:event.id,template_id:t.id,template_version:t.version})}/>}<RunList d={d} data={data} enabled={canWork(profile)} busy={c.busy} act={act}/></>}
 {page==='admin'&&<section className="card"><h2>Event connection</h2>{!event?<p>Activate an event below before configuring its schedule.</p>:d.can_manage?<form key={d.config?.version||0} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act('config',{event_id:event.id,version:d.config?.version||0,team_number:Number(f.get('team')),tba_event_key:String(f.get('tba')).trim(),nexus_event_key:String(f.get('nexus')).trim()},()=>void c.refresh(true));}}><label>Team number<input name="team" type="number" min="1" max="99999" defaultValue={d.config?.team_number||4418} required/></label><label>TBA event key<input name="tba" defaultValue={d.config?.tba_event_key||''} placeholder="Event key from TBA" required pattern="[0-9]{4}[a-z0-9]{1,40}"/></label><label>Nexus event identifier<input name="nexus" defaultValue={d.config?.nexus_event_key||''}/></label><small>Identifiers only. API keys stay in server secrets.</small><button disabled={c.busy}>Save event connection</button></form>:<p>Competition leadership configures the connection.</p>}</section>}
 {['dashboard','matches','admin'].includes(page)&&<p className="muted">Schedule/results: <a href="https://www.thebluealliance.com/" target="_blank" rel="noreferrer">The Blue Alliance</a> · Live queue: <a href="https://frc.nexus/" target="_blank" rel="noreferrer">Nexus</a></p>}
 </div>;
}
function RunStarter({d,busy,enabled,kind,start}:{d:Context;busy:boolean;enabled:boolean;kind:string;start:(t:Template)=>void}){const [id,setId]=useState('');const choices=d.templates.filter(t=>t.active&&t.kind===kind);return <section className="card"><h3>{kind==='pre'?'Pre-match':kind==='post'?'Post-match inspection':'General'} checklist</h3>{choices.length?<form onSubmit={e=>{e.preventDefault();const t=choices.find(t=>t.id===id);if(t)start(t);}}><label>Template<select value={id} onChange={e=>setId(e.target.value)} required><option value="">Choose a template</option>{choices.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.version}</option>)}</select></label><button disabled={busy||!enabled||!id}>Start checklist</button></form>:<p>No active template of this type. Add your procedure in Checklists.</p>}</section>;}
function RunList({d,matchId,data,enabled,busy,act}:{d:Context;matchId?:string;data:Data;enabled:boolean;busy:boolean;act:(action:string,p:Record<string,unknown>)=>void}){return <>{d.runs.filter(r=>matchId?r.match_id===matchId:true).map(r=><section className="card" key={r.id}><h3>{r.name} · v{r.template_version}</h3><small>{d.matches.find(o=>o.id===r.match_id)?.match_key||'General'} · started {new Date(r.started_at).toLocaleString()}</small>{d.items.filter(i=>i.run_id===r.id).map(i=><label className="comp-item" key={i.id}><input type="checkbox" checked={!!i.completed_at} disabled={!enabled||busy} onChange={e=>act('item',{id:i.id,version:i.version,complete:e.target.checked})}/><span><strong>{i.text}</strong><small>{i.required?'Required':'Optional'}{i.blocking?' · BLOCKING':''}{i.area_id?' · '+(d.areas.find(a=>a.id===i.area_id)?.name||'Area'):''}</small>{i.completed_at&&<small>Completed by {data.profiles.find(p=>p.id===i.completed_by)?.display_name||'Team member'} · {when(i.completed_at)}</small>}</span></label>)}</section>)}</>;}
function TemplateEditor({template:t,d,busy,cancel,save}:{template:Partial<Template>;d:Context;busy:boolean;cancel:()=>void;save:(p:Record<string,unknown>)=>void}){
 const [items,setItems]=useState<TemplateItem[]>(t.items||[{...blank}]);
 const change=(idx:number,p:Partial<TemplateItem>)=>setItems(items.map((i,n)=>n===idx?{...i,...p}:i));
 const move=(idx:number,by:number)=>{const a=[...items];[a[idx],a[idx+by]]=[a[idx+by],a[idx]];setItems(a);};
 return <form className="card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({id:t.id,version:t.version,active:t.active??true,name:f.get('name'),description:f.get('description'),kind:f.get('kind'),items});}}><h3>{t.id?'Edit':'Create'} template</h3><label>Name<input name="name" required maxLength={120} defaultValue={t.name}/></label><label>Description<input name="description" maxLength={1000} defaultValue={t.description}/></label><label>Type<select name="kind" defaultValue={t.kind}><option value="pre">Pre-match</option><option value="post">Post-match</option><option value="general">General</option></select></label>{items.map((i,n)=><fieldset key={n}><legend>Item {n+1}</legend><label>Item text<input value={i.text} required maxLength={300} onChange={e=>change(n,{text:e.target.value})}/></label><div className="comp-inline"><label><input type="checkbox" checked={i.required} onChange={e=>change(n,{required:e.target.checked})}/> Required</label><label><input type="checkbox" checked={i.blocking} onChange={e=>change(n,{blocking:e.target.checked})}/> Blocking</label></div><label>Area (optional)<select value={i.area_id||''} onChange={e=>change(n,{area_id:e.target.value||null})}><option value="">Any area</option>{d.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="comp-inline"><button type="button" disabled={n===0} onClick={()=>move(n,-1)}>Move up</button><button type="button" disabled={n===items.length-1} onClick={()=>move(n,1)}>Move down</button><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,idx)=>idx!==n))}>Remove item</button></div></fieldset>)}<div className="comp-inline"><button type="button" disabled={items.length>=60} onClick={()=>setItems([...items,{...blank}])}>Add item</button><button disabled={busy}>Save template</button><button type="button" onClick={cancel}>Cancel</button></div><p>Existing runs keep their original items and version.</p></form>;
}
